package com.uade.dam.demo.entity;

public enum Specialty {
    UROLOGO,
    CARDIOLOGO,
    PSIQUIATRA,
    PEDIATRA,
    DERMATOLOGO,
    GINECOLOGO,
    NEUROLOGO,
    TRAUMATOLOGO,
    OTORRINOLARINGOLOGO,
    OFTALMOLOGO,
    NEFROLOGO,
    ENDOCRINOLOGO,
    ONCOLOGO,
    INTERNISTA,
    ANESTESIOLOGO,
    GASTROENTEROLOGO,
    NEUMOLOGO,
    REUMATOLOGO,
    CIRUJANO_GENERAL,
    MEDICO_GENERAL
}